alias: Door open detected while away
trigger:
  platform: state
  entity_id: group.deuren
  from: 'off'
  to: 'on'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'not_home'
action:
  service: notify.telegram_koen
  data:
    title: Deur open!
    message: Deur open!
    data:
      photo:
        - url: !secret foscam_url
          caption: 'Deur open!'
