alias: 'Close carport at 22:00'
trigger:
  platform: time
  after: '22:00:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed 
    - thu
    - fri
    - sat
    - sun
action:
    service: cover.close_cover
    entity_id: cover.carport
