alias: motion detected while away
trigger:
  platform: state
  entity_id: light.motionschuur
  from: 'off'
  to: 'on'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'not_home'
action:
  service: notify.telegram_koen
  data:
    title: ''
    message: Motion detected!
    data:
      photo:
        - url: !secret foscam_url
          caption: 'Motion detected!'
